theme: jekyll-theme-minimal
title: samco
description: Personal homepage for swcollard's blog and projects
github_username: swcollard
paginate: 5
markdown: kramdown
permalink: /:year/:title:output_ext
