title: Samuel Collard
description: Personal homepage for swcollard's blog and projects
github_username: swcollard
markdown: kramdown
permalink: /:year/:title:output_ext

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - docs/
  - .superpowers/
  - Gemfile
  - Gemfile.lock
  - README.md
